apiVersion: 1

datasources:
  - name: InfluxDB-IxOS
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: keysight
      defaultBucket: ixosChassisStatistics
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
    editable: true
    isDefault: true

